export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "C++"
  | "CUDA"
  | "ROS"
  | "ROS2"
  | "Deep Learning"
  | "Computer Vision"
  | "YOLO"
  | "IoT"
  | "MQTT"
  | "Embedded Systems"
  | "STM32"
  | "Raspberry Pi"
  | "ESP32"
  | "Node-RED"
  | "Robotics"
  | "FPGA"
  | "Verilog"
  | "Digital Design"
  | "PID Control"
  | "Hardware Design"
  | "Analog Electronics"
  | "Audio Engineering"
  | "Mobile App";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "AI/ML"
  | "Robotics"
  | "IoT"
  | "Hardware"
  | "Computer Vision"
  | "Audio"
  | "Research"
  | "FPGA"
  | "Embedded Systems";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
