export const siteConfig = {
  name: "Dinethra Rajapaksha | Developer Portfolio",
  authorName: "Dinethra Rajapaksha",
  username: "DinethraDivanjana2001",
  description:
    "Dinethra Rajapaksha - B.Sc. Engineering student at University of Moratuwa specializing in Electronic and Telecommunication Engineering. Passionate about IoT, Machine Learning, and Software Development.",
  url: "https://dinethrarajapaksha.vercel.app",
  links: {
    twitter: "https://x.com/DinethraDivanjana2001",
    github: "https://github.com/DinethraDivanjana2001/",
    linkedin: "https://www.linkedin.com/in/dinethra-rajapaksha-7224b3365/",
    email: "divanjanad@gmail.com",
  },
  ogImage: "https://dinethrarajapaksha.vercel.app/profile-img.jpg",
  iconIco: "/logo.png",
  logoIcon: "/logo.png",
  keywords: [
    "Dinethra Rajapaksha",
    "AI & Machine Learning",
    "Computer Vision",
    "Software Development",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
