export const siteConfig = {
  name: "Dinethra Rajapaksha | Developer Portfolio",
  authorName: "Dinethra Rajapaksha",
  username: "namanbarkiya",
  description:
    "Dinethra Rajapaksha's portfolio - A modern, responsive Next.js portfolio for developers. This open-source template can be customized to showcase your own skills, projects, and professional experience.",
  url: "https://nbarkiya.xyz",
  links: {
    twitter: "https://x.com/namanbarkiya",
    github: "https://github.com/DinethraDivanjana2001/",
    linkedin: "https://www.linkedin.com/in/dinethra-rajapaksha-7224b3365/",
    email: "divanjanad@gmail.com",
  },
  ogImage: "https://nbarkiya.xyz/profile-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png",
  keywords: [
    "Dinethra Rajapaksha",
    "AI & Machine Learning",
    "Computer Vision",
    "Software Development",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
